build:
    environment:
        php:
            version: "7.1"
            ini:
                'date.timezone': 'Europe/Berlin'
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover'
                coverage:
                    file: 'clover'
                    format: 'clover'
checks:
    php: true