build:
    environment:
        php:
            version: "7.1"
            ini:
                'date.timezone': 'Europe/Berlin'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'clover'
checks:
    php: true